[[getting-started]]
== Getting started

To start reporting your Go application's performance to Elastic APM, we need to do a few things:

1. Install the Go agent package.
2. Instrument your application's source code.
3. Configure the application to send data to your Elastic APM server.

Below we'll look at installing the Go agent and instrumenting your application
code. For the final step, see the <<configuration>> section.

[[installation]]
=== Installation

Install the Elastic APM Go agent package using `go get`:

[source,bash]
----
go get go.elastic.co/apm
----

==== Requirements

The Go agent is tested with Go 1.8+ on Linux, Windows and MacOS.

[[instrumenting-source]]
=== Instrumenting Go Source Code

At present, Go applications must be instrumented manually at the source code level.
Where possible, you should use the <<builtin-modules, built-in instrumentation modules>>
to report transactions served by web and RPC frameworks in your application. If the
built-in modules are not suitable, please refer to <<custom-instrumentation, Custom Instrumentation>>.

[[builtin-modules]]
==== Built-in Modules

Below we describe the built-in instrumentation modules.

For each of the server instrumentation modules, a transaction is reported for each handled
request. The transaction will be stored in the request context, which can be obtained through
that framework's API. The request context can be used for reporting <<custom-instrumentation-spans, custom spans>>.

[[builtin-modules-apmecho]]
===== module/apmecho
Package apmecho provides middleware for the https://github.com/labstack/echo[Echo] web framework.

For each request, a transaction is stored in the request context, which can be obtained via
https://godoc.org/github.com/labstack/echo#Context[echo.Context]`.Request().Context()` in your handler.

[source,go]
----
import (
	"github.com/labstack/echo"
	"go.elastic.co/apm/module/apmecho"
)

func main() {
	e := echo.New()
	e.Use(apmecho.Middleware())
	...
}
----

The apmecho middleware will recover panics and send them to Elastic APM,
so you do not need to install the echo/middleware.Recover middleware.

[[builtin-modules-apmgin]]
===== module/apmgin
Package apmgin provides middleware for the https://gin-gonic.github.io/gin/[Gin] web framework.

For each request, a transaction is stored in the request context, which can be obtained via
https://godoc.org/github.com/gin-gonic/gin#Context[gin.Context]`.Request.Context()` in your handler.

[source,go]
----
import (
	"go.elastic.co/apm/module/apmgin"
)

func main() {
	engine := gin.New()
	engine.Use(apmgin.Middleware(engine))
	...
}
----

The apmgin middleware will recover panics and send them to Elastic APM, so you do not need to install the gin.Recovery middleware.

[[builtin-modules-apmbeego]]
===== module/apmbeego
Package apmbeego provides middleware for the https://beego.me/[Beego] web framework.

For each request, a transaction is stored in the request context, which can be obtained via
https://godoc.org/github.com/astaxie/beego/context#Context[beego/context.Context]`.Request.Context()`
in your controller.

[source,go]
----
import (
	"github.com/astaxie/beego"

	"go.elastic.co/apm/module/apmbeego"
)

type thingController struct{beego.Controller}

func (c *thingController) Get() {
	span, _ := apm.StartSpan(c.Ctx.Request.Context(), "thingController.Get", "controller")
	span.End()
	...
}

func main() {
	beego.Router("/", &testController{})
	beego.Router("/thing/:id:int", &testController{}, "get:Get")
	beego.RunWithMiddleWares("localhost:8080", apmbeego.Middleware())
}
----

[[builtin-modules-apmgorilla]]
===== module/apmgorilla
Package apmgorilla provides middleware for the http://www.gorillatoolkit.org/pkg/mux[Gorilla Mux] router.

For each request, a transaction is stored in the request context, which can be obtained via
https://golang.org/pkg/net/http/#Request[http.Request]`.Context()` in your handler.

[source,go]
----
import (
	"github.com/gorilla/mux"

	"go.elastic.co/apm/module/apmgorilla"
)

func main() {
	router := mux.NewRouter()
	router.Use(apmgorilla.Middleware())
	...
}
----

The apmgorilla middleware will recover panics and send them to Elastic APM, so you do not need to install any other recovery middleware.

[[builtin-modules-apmgrpc]]
===== module/apmgrpc
Package apmgrpc provides server and client interceptors for https://github.com/grpc/grpc-go[gRPC-Go].
Server interceptors report transactions for each incoming request, while client interceptors
report spans for each outgoing request. For each RPC served, a transaction is stored in the
context passed into the method.

[source,go]
----
import (
	"go.elastic.co/apm/module/apmgrpc"
)

func main() {
	server := grpc.NewServer(grpc.UnaryInterceptor(apmgrpc.NewUnaryServerInterceptor()))
	...
	conn, err := grpc.Dial(addr, grpc.WithUnaryInterceptor(apmgrpc.NewUnaryClientInterceptor()))
	...
}
----

The server interceptor can optionally be made to recover panics, in the same way as
https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/recovery[grpc_recovery].
The apmgrpc server interceptor will always send panics it observes as errors to the Elastic APM server.
If you want to recover panics but also want to continue using grpc_recovery, then you should ensure
that it comes before the apmgrpc interceptor in the interceptor chain, or panics will not be captured
by apmgrpc.

[source,go]
----
server := grpc.NewServer(grpc.UnaryInterceptor(
	apmgrpc.NewUnaryServerInterceptor(apmgrpc.WithRecovery()),
))
...
----

There is currently no support for intercepting at the stream level. Please file an issue and/or
send a pull request if this is something you need.

[[builtin-modules-apmhttp]]
===== module/apmhttp
Package apmhttp provides a low-level `net/http` middleware handler. Other web middleware should
typically be based off this.

For each request, a transaction is stored in the request context, which can be obtained via
https://golang.org/pkg/net/http/#Request[http.Request]`.Context()` in your handler.

[source,go]
----
import (
	"go.elastic.co/apm/module/apmhttp"
)

func main() {
	var myHandler http.Handler = ...
	tracedHandler := apmhttp.Wrap(myHandler)
}
----

The apmhttp handler will recover panics and send them to Elastic APM.

Package apmhttp also provides functions for instrumenting an `http.Client` or `http.RoundTripper`
such that outgoing requests are traced as spans, if the request context includes a transaction.

[source,go]
----
import (
	"net/http"
	"golang.org/x/net/context/ctxhttp"
	"go.elastic.co/apm/module/apmhttp"
)

var tracingClient = apmhttp.WrapClient(http.DefaultClient)

func serverHandler(w http.ResponseWriter, req *http.Request) {
	resp, err := ctxhttp.Get(req.Context(), tracingClient, "http://backend.local/foo")
	...
}

func main() {
	http.ListenAndServe(":8080", apmhttp.Wrap(http.HandlerFunc(serverHandler)))
}
----

[[builtin-modules-apmhttprouter]]
===== module/apmhttprouter
Package apmhttprouter provides a low-level middleware handler for https://github.com/julienschmidt/httprouter[httprouter].

For each request, a transaction is stored in the request context, which can be obtained via
https://golang.org/pkg/net/http/#Request[http.Request]`.Context()` in your handler.

[source,go]
----
import (
	"github.com/julienschmidt/httprouter"

	"go.elastic.co/apm/module/apmhttprouter"
)

func main() {
	router := httprouter.New()

	const route = "/my/route"
	router.GET(route, apmhttprouter.Wrap(h, route))
	...
}
----

https://github.com/julienschmidt/httprouter/pull/139[httprouter does not provide a means of obtaining the matched route], hence the route must be passed into the wrapper.

Alternatively you can use the apmhttprouter.Router type, which wraps httprouter.Router,
providing the same API and instrumenting added routes. To use this wrapper type, you
should rewrite your use of `httprouter.New` to `apmhttprouter.New`; the returned type
is `*apmhttprouter.Router`, and not `*httprouter.Router`.

[source,go]
----
import (
	"github.com/julienschmidt/httprouter"

	"go.elastic.co/apm/module/apmhttprouter"
)

func main() {
	router := apmhttprouter.New()

	router.GET(route, h)
	...
}
----

===== module/apmlambda
Package apmlambda intercepts requests to your AWS Lambda function invocations.

experimental[]

Importing the package is enough to report the function invocations.

[source,go]
----
import (
	_ "go.elastic.co/apm/module/apmlambda"
)
----

We currently do not expose the transactions via context; when we do, it will be
necessary to make a small change to your code to call apmlambda.Start instead of
lambda.Start.

[[builtin-modules-apmsql]]
===== module/apmsql
Package apmsql provides a means of wrapping `database/sql` drivers so that queries and other
executions are reported as spans within the current transaction.

To trace SQL queries, you should register drivers using apmsql.Register and obtain connections
with apmsql.Open. The parameters are exactly the same as if you were to call sql.Register
and sql.Open respectively.

As a convenience, we also provide packages which will automatically register popular drivers
with apmsql.Register:

- module/apmsql/pq (github.com/lib/pq)
- module/apmsql/mysql (github.com/go-sql-driver/mysql)
- module/apmsql/sqlite3 (github.com/mattn/go-sqlite3)

[source,go]
----
import (
	"go.elastic.co/apm/module/apmsql"
	_ "go.elastic.co/apm/module/apmsql/pq"
	_ "go.elastic.co/apm/module/apmsql/sqlite3"
)

func main() {
	db, err := apmsql.Open("pq", "postgres://...")
	db, err := apmsql.Open("sqlite3", ":memory:")
}
----

Spans will be created for queries and other statement executions if the context methods are
used, and the context includes a transaction.

[[builtin-modules-apmgorm]]
===== module/apmgorm
Package apmgorm provides a means of instrumenting http://gorm.io[GORM] database operations.

To trace `GORM` operations, import the appropriate `apmgorm/dialects` package (instead of the
`gorm/dialects` package), and use `apmgorm.Open` (instead of `gorm.Open`). The parameters are
exactly the same.

Once you have a `*gorm.DB` from `apmgorm.Open`, you can call `apmgorm.WithContext` to
propagate a context containing a transaction to the operations:

[source,go]
----
import (
	"go.elastic.co/apm/module/apmgorm"
	_ "go.elastic.co/apm/module/apmgorm/dialects/postgres"
)

func main() {
	db, err := apmgorm.Open("postgres", "")
	...
	db = apmgorm.WithContext(ctx, db)
	db.Find(...) // creates a "SELECT FROM <foo>" span
}
----

[[builtin-modules-apmgocql]]
===== module/apmgocql
Package apmgocql provides a means of instrumenting https://github.com/gocql/gocql[gocql] so
that queries are reported as spans within the current transaction.

To report `gocql` queries, you can construct an `apmgocql.Observer` and assign it to
the `QueryObserver` and `BatchObserver` fields of `gocql.ClusterConfig`, or install it
into a specific `gocql.Query` or `gocql.Batch` via their `Observer` methods.

Spans will be created for queries as long as they have context associated, and the
context includes a transaction.

[source,go]
----
import (
	"github.com/gocql/gocql"

	"go.elastic.co/apm/module/apmgocql"
)

func main() {
	observer := apmgocql.NewObserver()
	config := gocql.NewCluster("cassandra_host")
	config.QueryObserver = observer
	config.BatchObserver = observer

	session, err := config.CreateSession()
	...
	err = session.Query("SELECT * FROM foo").WithContext(ctx).Exec()
	...
}
----

[[builtin-modules-apmredigo]]
===== module/apmredigo
Package apmredigo provides a means of instrumenting https://github.com/gomodule/redigo[Redigo]
so that Redis commands are reported as spans within the current transaction.

To report Redis commands, you can use the top-level `Do` or `DoWithTimeout` functions.
These functions have the same signature as the `redis.Conn` equivalents apart from an
initial `context.Context` parameter. If the context passed in contains a sampled
transaction, a span will be reported for the Redis command.

Another top-level function, `Wrap`, is provided to wrap a `redis.Conn` such that its
`Do` and `DoWithTimeout` methods call the above mentioned functions. Initially, the
wrapped connection will be associated with the background context; its `WithContext`
method may be used to obtain a shallow copy with another context. For example, in an
HTTP middleware you might bind a connection to the request context, which would
associate spans with the request's APM transaction.

[source,go]
----
import (
	"net/http"

	"github.com/gomodule/redigo/redis"

	"go.elastic.co/apm/module/apmredigo"
)

var redisPool *redis.Pool // initialized at program startup

func handleRequest(w http.ResponseWriter, req *http.Request) {
	// Wrap and bind redis.Conn to request context. If the HTTP
	// server is instrumented with Elastic APM (e.g. with apmhttp),
	// Redis commands will be reported as spans within the request's
	// transaction.
	conn := apmredigo.Wrap(redisPool.Get()).WithContext(req.Context())
	defer conn.Close()
	...
}
----

[[builtin-modules-apmrestful]]
===== module/apmrestful
Package apmrestful provides a https://github.com/emicklei/go-restful[go-restful] filter
for tracing requests, and capturing panics.

For each request, a transaction is stored in the request context, which can be obtained via
https://golang.org/pkg/net/http/#Request[http.Request]`.Context()` in your handler.

[source,go]
----
import (
	"github.com/emicklei/go-restful"

	"go.elastic.co/apm/module/apmrestful"
)

func init() {
	// Trace all requests to web services registered with the default container.
	restful.Filter(apmrestful.Filter())
}

func main() {
	var ws restful.WebService
	ws.Path("/things").Consumes(restful.MIME_JSON, restful.MIME_XML).Produces(restful.MIME_JSON, restful.MIME_XML)
	ws.Route(ws.GET("/{id:[0-1]+}").To(func(req *restful.Request, resp *restful.Response) {
		// req.Request.Context() should be propagated to downstream operations such as database queries.
	}))
	...
}
----

[[builtin-modules-apmlogrus]]
===== module/apmlogrus
Package apmlogrus provides a https://github.com/sirupsen/logrus[logrus] Hook
implementation for sending error messages to Elastic APM, as well as a function
for adding trace context fields to log records.

[source,go]
----
import (
	"github.com/sirupsen/logrus"

	"go.elastic.co/apm/module/apmlogrus"
)

func init() {
	// apmlogrus.Hook will send "error", "panic", and "fatal" level log messages to Elastic APM.
	logrus.AddHook(&apmlogrus.Hook{})
}

func handleRequest(w http.ResponseWriter, req *http.Request) {
	// apmlogrus.TraceContext extracts the transaction and span (if any) from the given context,
	// and returns logrus.Fields containing the trace, transaction, and span IDs.
	traceContextFields := apmlogrus.TraceContext(req.Context())
	logrus.WithFields(traceContextFields).Debug("handling request")

	// Output:
	// {"level":"debug","msg":"handling request","time":"1970-01-01T00:00:00Z","trace.id":"67829ae467e896fb2b87ec2de50f6c0e","transaction.id":"67829ae467e896fb"}
}
----

[[builtin-modules-apmzap]]
===== module/apmzap
Package apmzap provides a https://godoc.org/go.uber.org/zap/zapcore#Core[go.uber.org/zap/zapcore.Core]
implementation for sending error messages to Elastic APM, as well as a function
for adding trace context fields to log records.

[source,go]
----
import (
	"go.uber.org/zap"

	"go.elastic.co/apm/module/apmzap"
)

// apmzap.Core.WrapCore will wrap the core created by zap.NewExample
// such that logs are also sent to the apmzap.Core.
//
// apmzap.Core will send "error", "panic", and "fatal" level log
// messages to Elastic APM.
var logger = zap.NewExample(zap.WrapCore((&apmzap.Core{}).WrapCore))

func handleRequest(w http.ResponseWriter, req *http.Request) {
	// apmzap.TraceContext extracts the transaction and span (if any)
	// from the given context, and returns zap.Fields containing the
	// trace, transaction, and span IDs.
	traceContextFields := apmzap.TraceContext(req.Context())
	logger.With(traceContextFields...).Debug("handling request")

	// Output:
	// {"level":"debug","msg":"handling request","trace.id":"67829ae467e896fb2b87ec2de50f6c0e","transaction.id":"67829ae467e896fb"}
}
----

[[custom-instrumentation]]
==== Custom instrumentation

To report on the performance of transactions served by your application, you can use the Go
agent's <<api, API>>. Instrumentation refers to modifying your application code to report:

 - transactions
 - spans within transactions
 - errors

A transaction represents a top-level operation in your application, such as an HTTP or RPC
request. A span represents an operation within a transaction, such as a database query, or
a request to another service. Errors may refer to Go errors, or panics.

To report these things, you will use a <<tracer-api, apm.Tracer>> -- typically
`apm.DefaultTracer`, which is configured via environment variables. In the code
examples below we will refer to `apm.DefaultTracer`. Please refer to the <<api, API documentation>>
for a more thorough description of the types and methods.

===== Transactions

To report a transaction, you call <<tracer-api-start-transaction, apm.DefaultTracer.StartTransaction>>
with the transaction name and type. This returns a `Transaction` object; the transaction
can be customized with additional context before you call its `End` method to indicate
that the transaction has completed. Once the transaction's `End` method is called, it
will be enqueued for sending to the Elastic APM server, and made available to the APM UI.

[source,go]
----
tx := apm.DefaultTracer.StartTransaction("GET /api/v1", "request")
defer tx.End()
...
tx.Result = "HTTP 2xx"
tx.Context.SetTag("region", "us-east-1")
----

The agent supports sampling transactions: non-sampled transactions will be still be
reported, but with limited context and without any spans. To determine whether a
transaction is sampled, use the `Transaction.Sampled` method; if it returns false,
you should avoid unnecessary storage or processing required for setting transaction
context.

Once you have started a transaction, you can include it in a `context` object for
propagating throughout the application. See <<custom-instrumentation-propagation, context propagation>>
for more details.

[source,go]
----
ctx = apm.ContextWithTransaction(ctx, tx)
----

[[custom-instrumentation-spans]]
===== Spans

To report an operation within a transaction, you should use <<transaction-start-span, Transaction.StartSpan>>
or <<apm-start-span, apm.StartSpan>> to start a span given a transaction or a `context`
containing a transaction, respectively. Like a transaction, a span has a name and a type. In addition,
a span can have a parent span within the same transaction. If the context provided to `apm.StartSpan`
contains a span, then that will be considered the parent. See <<custom-instrumentation-propagation, context propagation>>
for more details.

[source,go]
----
span, ctx := apm.StartSpan(ctx, "SELECT FROM foo", "db.mysql.query")
defer span.End()
----

`Transaction.StartSpan` and `apm.StartSpan` will always return a non-nil `Span`, even if the
transaction is nil. It is always safe to defer a call to the span's End method. If setting the span's
context would incur significant overhead, you may want to check if the span is dropped first, by calling
the `Span.Dropped` method.

[[custom-instrumentation-propagation]]
===== Context propagation

In Go, https://golang.org/pkg/context/[context] is used to propagate request-scoped values along a call
chain, potentially crossing between goroutines and between processes. For servers based on `net/http`,
each request contains an independent context object, which allows adding values specific to that particular
request.

When you start a transaction, you can add it to a context object using
<<apm-context-with-transaction, apm.ContextWithTransaction>>. This context object can be
later passed to <<apm-transaction-from-context, apm.TransactionFromContext>> to obtain
the transaction, or into <<apm-start-span, apm.StartSpan>> to start a span.

The simplest way to create and propagate a span is by using <<apm-start-span, apm.StartSpan>>,
which takes a context and returns a span. The span will be created as a child of the span most recently
added to this context, or a transaction added to the context as described above. If the context contains
neither a transaction nor a span, then the span will be dropped (i.e. will not be reported to the APM Server.)

For example, take a simple CRUD-type web service, which accepts requests over HTTP and then makes
corresponding database queries. For each incoming request, a transaction will be started and added to the
request context automatically. This context needs to be passed into method calls within the handler manually
in order to create spans within that transaction, e.g. to measure the duration of SQL queries.

[source,go]
----
import (
	"net/http"

	"go.elastic.co/apm"
	"go.elastic.co/apm/module/apmhttp"
	"go.elastic.co/apm/module/apmsql"
	_ "go.elastic.co/apm/module/apmsql/pq"
)

var db *sql.DB

func init() {
	// apmsql.Open wraps sql.Open, in order
	// to add tracing to database operations.
	db, _ = apmsql.Open("postgres", "")
}

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/", handleList)

	// apmhttp.Wrap instruments an http.Handler, in order
	// to report any request to this handler as a transaction,
	// and to store the transaction in the request's context.
	handler := apmhttp.Wrap(mux)
	http.ListenAndServe(":8080", handler)
}

func handleList(w http.ResponseWriter, req *http.Request) {
	// By passing the request context down to getList, getList can add spans to it.
	ctx := req.Context()
	getList(ctx)
	...
}

func getList(ctx context.Context) (
	// When getList is called with a context containing a transaction or span,
	// StartSpan creates a child span. In this example, getList is always called
	// with a context containing a transaction for the handler, so we should
	// expect to see something like:
	//
	//     Transaction: handleList
	//         Span: getList
	//             Span: SELECT FROM items
	//
	span, ctx := apm.StartSpan(ctx, "getList", "custom")
	defer span.End()

	// NOTE: The context object ctx returned by StartSpan above contains
	// the current span now, so subsequent calls to StartSpan create new
	// child spans.

	// db was opened with apmsql, so queries will be reported as
	// spans when using the context methods.
	rows, err := db.QueryContext(ctx, "SELECT * FROM items")
	...
	rows.Close()
}
----

===== Panic recovery and errors

If you want to recover panics, and report them along with your transaction, you can use the
<<tracer-recovered, Tracer.Recovered>> method in a recovery function. There are also methods for reporting
non-panic errors: <<tracer-new-error, Tracer.NewError>>, <<tracer-new-error-log, Tracer.NewErrorLog>>, and
<<apm-captureerror, apm.CaptureError>>.

[source,go]
----
defer func() {
	if v := recover(); v != nil {
		e := apm.DefaultTracer.Recovered()
		e.SetTransaction(tx) // or e.SetSpan(span)
		e.Send()
	}
}()
----

See the <<error-api, Error API>> for details and examples of the other methods.
