[[introduction]]
== Introduction

The Elastic APM Go Agent enables you to trace the execution of operations in your https://golang.org/[Go]
applications, sending performance metrics and errors to the Elastic APM server.
It has built-in support for popular frameworks and toolkits,
like http://www.gorillatoolkit.org/[Gorilla] and https://gin-gonic.github.io/gin/[Gin],
as well as support for instrumenting Go's built-in https://golang.org/pkg/net/http/[net/http],
https://golang.org/pkg/database/sql/[database/sql] drivers.
The Agent also offers an <<api>> for custom instrumentation.

[float]
[[how-it-works]]
=== How does the Agent work?

The Agent auto-instruments <<supported-tech>> and records interesting events,
like spans for database queries and transactions for incoming HTTP requests.
To do this, it [[NEED_CONTENT_HERE]]

[float]
[[additional-components]]
=== Additional Components

APM Agents work in conjunction with the {apm-server-ref-v}/index.html[APM Server], {ref}/index.html[Elasticsearch], and {kibana-ref}/index.html[Kibana].
Please view the {apm-overview-ref-v}/index.html[APM Overview] for details on how these components work together. 
