#!/bin/bash

set -e

_PKGS=$(go list -f '{{printf "\t%q: {},\n" .ImportPath}}' "$@")

cat > library.go <<EOF
// Code generated by "go generate". DO NOT EDIT.

package stacktrace

var libraryPackages = map[string]struct{}{
$_PKGS
}

func isLibraryPackage(pkg string) bool {
	_, ok := libraryPackages[pkg]
	return ok
}
EOF

gofmt -w library.go
