name: microbenchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
    tags:
      - "v*.*.*"

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  microbenchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/run-microbenchmark@github-microbenchmark
        with:
          vault-url: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
          #slack-channel: "#apm-agent-go"
          script: scripts/ci/bench.sh
          environments:
            GO_VERSION=stable
