name: microbenchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
    tags:
      - "v*.*.*"

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

env:
  GO_VERSION: 1.15.10

jobs:
  microbenchmark:
    runs-on: ubuntu-latest
    # wait up to 1 hour
    timeout-minutes: 60
    steps:
      - id: buildkite
        name: Run buildkite pipeline
        uses: elastic/apm-pipeline-library/.github/actions/buildkite@current
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          pipeline: apm-agent-microbenchmark
          waitFor: true
          printBuildLogs: true
          buildEnvVars: |
            script=scripts/ci/bench.sh
            repo=apm-agent-go
            sha=${{ github.sha }}
            GO_VERSION=${{ env.GO_VERSION }}

      - if: ${{ failure() }}
        uses: elastic/apm-pipeline-library/.github/actions/slack-message@current
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          channel: "#apm-agent-go"
          message: |
            :ghost: [${{ github.repository }}] microbenchmark *${{ github.ref_name }}* failed to run in Buildkite.
            Build: (<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|here>)
